const PRODUCTS = [
  // ─────────── PRODUITS EXISTANTS (noms commerciaux) ───────────
  { id:1, name:"Paddle Pro Aventure 11'6\"", category:"Paddles", price:449.00, original:549.00, badge:"new", emoji:"🏄", img:"paddle-1.jpg.jpg", images:["paddle-1.jpg.jpg","paddle-2.jpg.jpg","paddle-3.jpg.jpg"], stars:4.9, reviews:128, desc:"Stand Up Paddle gonflable ultra-stable 11'6\". Supporte jusqu'à 195 kg. Idéal rivière, lac et mer.", details:"Dimensions : 350×86×15 cm (11'6\"×34\"×6\"). Poids max : 195 kg. Pression : 12–15 PSI. Construction Drop-Stitch haute densité. Livré avec pagaie, pompe, leash et sac de transport.", filter:["nouveautes","populaire","promo"] },
  { id:2, name:"Scooter Sous-Marin Explorer Pro", category:"Seaglides", price:1290.00, original:1490.00, badge:"new", emoji:"🤿", img:"seaglide-1.jpg.jpg", images:["seaglide-1.jpg.jpg","seaglide-2.jpg.jpg","seaglide-3.jpg.jpg"], stars:4.9, reviews:34, desc:"Scooter sous-marin connecté. 3 vitesses, écran LED, se fixe aussi sur paddle et kayak.", details:"Moteur puissant 3 vitesses. Écran LED batterie et mode. Fixation universelle paddle/kayak. Bandoulières incluses. Étanche eau douce et salée. Batterie rechargeable haute autonomie.", filter:["nouveautes","populaire","promo"] },
  { id:3, name:"Transat Flottant Paradise", category:"Détente", price:39.90, original:54.90, badge:"sale", emoji:"🪑", img:"chaise-1.jpg.jpg", images:["chaise-1.jpg.jpg","chaise-2.jpg.jpg","chaise-3.jpg.jpg"], stars:4.8, reviews:156, desc:"Chaise longue gonflable flottante avec dossier. Motif tropical. Confort et stabilité dans l'eau.", details:"Dimensions : 76×41×61 cm. Dossier confortable et assise immergée. Tissu tropical résistant aux UV. Gonflage rapide. Sangles de maintien. Capacité max : 100 kg.", filter:["nouveautes","populaire","promo"] },
  { id:4, name:"Mini Ventilateur AirBreeze", category:"Accessoires", price:29.90, original:39.90, badge:"new", emoji:"💨", img:"airflow-1.jpg.jpg", images:["airflow-1.jpg.jpg","airflow-2.jpg.jpg","airflow-3.jpg.jpg"], stars:4.9, reviews:203, desc:"Mini ventilateur portable. Design premium, turbine dorée silencieuse. Idéal plage, piscine et terrasse.", details:"Turbine dorée silencieuse. 3 vitesses. Batterie USB-C (autonomie 8h). Boucle de suspension. Ultra-compact. 3 coloris.", filter:["nouveautes","populaire","promo"] },

  // ─────────── NOUVEAUX PRODUITS ───────────
  { id:5, name:"Filet de Beach Volley Aquatique", category:"Jeux d'Eau", price:59.90, original:79.90, badge:"new", emoji:"🏐", img:"Fillet de jeux.jpg", images:["Fillet de jeux.jpg","Fillet de jeux 2.jpg"], stars:4.8, reviews:74, desc:"Filet de volley flottant pour piscine et plage. Montage rapide, idéal pour les parties endiablées entre amis.", details:"Filet flottant ajustable. Poteaux gonflables stabilisés par lestage à eau. Largeur réglable. Résistant au chlore, au sel et aux UV. Livré avec ballon et sac. Parfait piscine, lac et bord de mer.", filter:["nouveautes","populaire"] },
  { id:6, name:"Paddle Board Rainbow Summer", category:"Paddles", price:399.00, original:499.00, badge:"sale", emoji:"🏄", img:"Paddel colors.jpg", images:["Paddel colors.jpg","Paddel colors 2.jpg","Paddel Colors 3.jpg"], stars:4.9, reviews:92, desc:"Stand Up Paddle gonflable aux couleurs vives de l'été. Stable, léger et ultra-tendance.", details:"Dimensions : 320×81×15 cm. Construction Drop-Stitch. Pression 12–15 PSI. Surface antidérapante. Coloris multicolores arc-en-ciel. Livré avec pagaie réglable, pompe, leash, ailerons et sac à dos de transport.", filter:["nouveautes","populaire","promo"] },
  { id:7, name:"Table Lounge Outdoor Premium", category:"Mobilier", price:189.00, original:249.00, badge:"new", emoji:"🪑", img:"Table extérieur.jpg", images:["Table extérieur.jpg","Table extérieure 2.jpg"], stars:4.7, reviews:48, desc:"Table d'extérieur élégante pour terrasse, jardin et bord de piscine. Design moderne et résistant.", details:"Structure résistante aux intempéries. Plateau facile à nettoyer. Pieds stabilisateurs antidérapants. Idéale terrasse, jardin et pool party. Montage simple et rapide.", filter:["nouveautes","populaire"] },
  { id:8, name:"Méga Blaster à Eau XXL", category:"Jeux d'Eau", price:24.90, original:34.90, badge:"sale", emoji:"🔫", img:"Pistolet à eau.jpg", images:["Pistolet à eau.jpg","Pistolet à eau 2.jpg"], stars:4.9, reviews:187, desc:"Pistolet à eau longue portée pour batailles d'été mémorables. Grand réservoir, jet puissant.", details:"Portée jusqu'à 10 m. Grand réservoir haute capacité. Pompe à action puissante. Poignée ergonomique antidérapante. Pour enfants et adultes. Matériau robuste résistant aux chocs.", filter:["nouveautes","populaire","promo"] },
  { id:9, name:"Table de Poker Casino Deluxe", category:"Jeux & Loisirs", price:299.00, original:399.00, badge:"new", emoji:"🃏", img:"Table de poker.jpg", images:["Table de poker.jpg","Table poker 2.jpg","Table poker 3.jpg"], stars:4.8, reviews:63, desc:"Table de poker professionnelle façon casino. Tapis feutré, repose-bras et emplacements jetons.", details:"Tapis feutré professionnel anti-reflet. Repose-bras rembourré tout autour. Emplacements pour jetons et porte-gobelets. Structure pliable pour rangement facile. Idéale soirées poker entre amis.", filter:["nouveautes","populaire","promo"] },
  { id:10, name:"Table de Poker Ronde Royale", category:"Jeux & Loisirs", price:329.00, original:429.00, badge:"new", emoji:"🃏", img:"Table poker rond.jpg", images:["Table poker rond.jpg","Table poker rond 2.jpg"], stars:4.8, reviews:41, desc:"Table de poker ronde conviviale pour parties à plusieurs. Finition premium et confort optimal.", details:"Format rond convivial jusqu'à 8 joueurs. Tapis feutré professionnel. Bordure rembourrée. Porte-gobelets intégrés. Pieds stables et robustes. Pour soirées casino réussies.", filter:["nouveautes","populaire","promo"] },
  { id:11, name:"Scooter Sous-Marin SeaJet", category:"Seaglides", price:990.00, original:1190.00, badge:"sale", emoji:"🤿", img:"Jet sous marin.jpg", images:["Jet sous marin.jpg","Jet sous marin 2.jpg"], stars:4.7, reviews:29, desc:"Scooter sous-marin compact et puissant pour explorer les fonds marins. Léger et maniable.", details:"Moteur électrique silencieux. Plusieurs vitesses. Poignées ergonomiques double prise. Étanche, conçu pour la plongée loisir. Batterie rechargeable. Léger et facile à transporter.", filter:["nouveautes","populaire","promo"] },
  { id:12, name:"Jet Ski Gonflable Wave Rider", category:"Jeux d'Eau", price:149.00, original:199.00, badge:"new", emoji:"🌊", img:"Jet ski gonflable.jpg", images:["Jet ski gonflable.jpg","Jet ski gonflable 2.jpg"], stars:4.8, reviews:56, desc:"Jet ski gonflable ludique pour grands et petits. Sensations garanties sur l'eau tout l'été.", details:"PVC haute résistance. Poignées de maintien robustes. Valves anti-retour pour gonflage rapide. Excellente flottabilité et stabilité. Idéal piscine, lac et mer calme. Plusieurs tailles d'utilisateur.", filter:["nouveautes","populaire"] },
  { id:13, name:"Table de Beer Pong Flottante", category:"Jeux d'Eau", price:44.90, original:59.90, badge:"sale", emoji:"🍻", img:"Table de beer pong.jpg", images:["Table de beer pong.jpg"], stars:4.9, reviews:138, desc:"Table de beer pong flottante pour animer vos pool parties. Emplacements gobelets intégrés.", details:"Plateau gonflable flottant avec 2×6 emplacements pour gobelets. PVC résistant. Glacière centrale intégrée. Livrée avec balles. L'accessoire indispensable des soirées piscine.", filter:["nouveautes","populaire","promo"] },
  { id:14, name:"Table de Jeux Flottante Conviviale", category:"Jeux d'Eau", price:54.90, original:74.90, badge:"new", emoji:"🎲", img:"Table de jeux assis.jpg", images:["Table de jeux assis.jpg","Table de jeux assis 2.jpg"], stars:4.7, reviews:52, desc:"Table de jeux flottante avec sièges intégrés. Profitez de l'eau confortablement installé entre amis.", details:"Plateau central avec sièges immergés tout autour. Porte-gobelets intégrés. PVC robuste résistant aux UV. Gonflage rapide. Idéale apéritifs et jeux dans la piscine.", filter:["nouveautes","populaire"] },
  { id:15, name:"Chaise Longue Flottante Lagon", category:"Détente", price:49.90, original:69.90, badge:"sale", emoji:"🏖️", img:"Chaise long piscine.jpg", images:["Chaise long piscine.jpg","Chaise longe piscine 2.jpg"], stars:4.9, reviews:174, desc:"Chaise longue flottante grand confort pour la piscine. Bronzez et détendez-vous au fil de l'eau.", details:"Assise et dossier ergonomiques. Repose-tête confortable. PVC épais résistant aux UV et au chlore. Gonflage rapide multi-chambres. Excellente flottabilité. Parfaite pour la détente au soleil.", filter:["nouveautes","populaire","promo"] },
  { id:16, name:"Paddle Aquapark Flypark XXL", category:"Paddles", price:259.00, original:329.00, badge:"new", emoji:"🏄", img:"Paddel flypark.jpg", images:["Paddel flypark.jpg","Paddel flypark 2.jpg"], stars:4.8, reviews:38, desc:"Plateforme paddle aquapark XXL pour s'amuser à plusieurs. Sauts, équilibre et fous rires garantis.", details:"Grande plateforme gonflable multi-personnes. Surface antidérapante. Poignées périphériques. PVC ultra-résistant. Valves haut débit. Idéale lac, mer et grand bassin. Sensations garanties.", filter:["nouveautes","populaire"] }
];
